### ISSUE TITLE
Default theme always resets to configured value

### ISSUE THREAD

**Issue by thany** [hipstersmoothie/storybook-dark-mode#179]
I added a default theme:

```javascript
export const parameters = {
  darkMode: {
    // ...
    current: 'light',
  },
};
```

This causes the theme to reset to `light` every time when selecting another story.

This is incorrect when considering the documention:

> Order of precedence for the initial color scheme:
> 
> 1. If the user has previously set a color theme it's used
> 2. The value you have configured for current parameter in your storybook
> 3. The OS color scheme preference

So, a previously set theme by the user should take precedence. And it'd make perfect sense if it did that.

**Comment by Develonaut** [comment]
I think this issue is in this hook: https://github.com/hipstersmoothie/storybook-dark-mode/blob/master/src/Tool.tsx#L181

The `current` value set in the store is being overwritten with the default that was defined in the parameters. I think it needs to be updated to prefer the store's current and fallback to the params current.

**Comment by hipstersmoothie** [comment]
Gonna close this since a pr was submitted to fix. if it persists feel free to create another PR
